# Generated by Django 6.0.4 on 2026-04-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alvara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18)),
                ('endereco', models.CharField(max_length=250)),
                ('responsavel', models.CharField(max_length=150)),
                ('emissao', models.DateField()),
                ('validade', models.DateField()),
                ('situacao', models.CharField(max_length=30)),
            ],
        ),
    ]
