# Generated by Django 6.0.4 on 2026-04-27 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguranca',
            name='situacao',
        ),
        migrations.AddField(
            model_name='seguranca',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguranca',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguranca',
            name='mae',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seguranca',
            name='naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segurancas_naturais', to='cadastro.municipio'),
        ),
        migrations.AddField(
            model_name='seguranca',
            name='pai',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seguranca',
            name='registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seguranca',
            name='rg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paginasistema',
            name='rota',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seguranca',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='seguranca',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa'),
        ),
        migrations.AlterField(
            model_name='seguranca',
            name='nome_completo',
            field=models.CharField(max_length=150),
        ),
    ]
