# Generated by Django 6.0.4 on 2026-04-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_seguranca_situacao_seguranca_data_admissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguranca',
            name='situacao',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20),
        ),
    ]
