# Generated by Django 6.0.4 on 2026-04-27 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_seguranca_situacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_guerra', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=150, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cidade_nascimento', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_nascimento', models.CharField(blank=True, max_length=2, null=True)),
                ('pai', models.CharField(blank=True, max_length=150, null=True)),
                ('mae', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
