# Generated by Django 6.0.4 on 2026-04-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_paginasistema_permissaousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='situacao',
            field=models.CharField(default='Ativa', max_length=30),
        ),
        migrations.AddField(
            model_name='seguranca',
            name='situacao',
            field=models.CharField(default='Ativo', max_length=30),
        ),
    ]
